mysql: # In dbconfig.yaml:
  # 主机地址
  host:
  # 端口
  port: 3306
  # 用户名
  user: root
  # 密码
  password:
  # 数据库名称
  db_name:
  # 打开数据库连接的最大数量
  max_open_conns: 100
  # 空闲连接池中连接的最大数量
  max_idle_conns: 100
  # 连接可复用的最大时间
  max_lifetime: 3600
  # 表前缀
  table_prefix: t_
  # 输入日志级别
  log_level: info

redis: # In redisconfig.yaml
  # Redis服务器地址列表
  address: addr:port
  # Redis身份验证的用户名（如果未使用，请留空）
  username: ''
  # Redis身份验证的密码
  password: 123456
  # 启用或禁用集群模式
  clusterMode: false
  # 要使用的数据库索引
  db:
  # 失败连接的最大重试尝试次数
  maxRetry: 10
  # 连接池大小
  poolSize: 10