### POST 添加新的物品
POST http://localhost:8000/v1/inventory/create
Content-Type: application/json

{
  "name": "macbook air",
  "picture": "ccc",
  "price": 12999,
  "count": 3
}

### POST 更新物品
POST http://localhost:8000/v1/inventory/update
Content-Type: application/json

{
  "id": 1,
  "name": "huawei",
  "picture": "aaaa",
  "price": 8299,
  "count": 15
}

### POST 物品秒杀
POST http://localhost:8000/v1/inventory/seckill
Content-Type: application/json

{
  "id": 1
}

### GET 获取物品
GET http://localhost:8000/v1/inventory/get

### GET 秒杀预热
GET http://localhost:8000/v1/inventory/load

